[project]
name = "mlops-lab1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mhamad Naser Dine", email = "mhamadnd100@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
mlops-lab1 = "mlops_lab1:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
